[tool.poetry]
name = "canvasrobot"
version = "0.8.0"
description = "Library which uses Canvasapi https://canvasapi.readthedocs.io/en/stable/getting-started.html to provide a CanvasRobot class."
authors = ["Nico de Groot <ndegroot0@gmail.com>",]
readme = "README.md"

[tool.poetry.scripts]
canvasrobot_cli = 'canvasrobot.main:run'
urltransform_cli = 'canvasrobot.urltransform:run'

[tool.poetry.dependencies]
python = ">=3.9,<4.0.0"
openpyxl = "*"
pydal = "*"
toml = "*"
keyring = "*"
requests = "*"
pyaml = "*"
rich = "*"
# canvasapi = {path="../canvasapi", develop = true}
#canvasapi = { git = "https://github.com/ndegroot/canvasapi", branch = "issue/440-allow-sis-ids" }
canvasapi ="*" # no sis_id!
attrs = "*"
result = "*"
pywebview = "^5.3.2"
pytz = "^2024.2"
arrow = "^1.3.0"


[tool.poetry.dev-dependencies]
pytest = "*"
mock = "*"
pylint = "*"
ruff = "*"
pymemcache = "*"
mypy = "*"
types-requests = "*"
types-pyyaml = "*"

[tool.poetry_bumpversion.file."canvasrobot/__init__.py"]


[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "mock",
    "pylint",
    "ruff",
    "pymemcache",
    "mypy",
    "types-requests",
    "types-pyyaml",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = [
    {name = "Nico de Groot", email = "ndegroot0@gmail.com"},
]
requires-python = "<4.0.0,>=3.9"
dependencies = [
    "openpyxl",
    "pydal",
    "toml",
    "keyring",
    "requests",
    "pyaml",
    "rich",
    "canvasapi",
    "attrs",
    "result",
    "pywebview<6.0.0,>=5.3.2",
    "pytz<2025.0,>=2024.2",
    "arrow<2.0.0,>=1.3.0",
]
name = "canvasrobot"
version = "0.8.0"
description = "Library which uses Canvasapi https://canvasapi.readthedocs.io/en/stable/getting-started.html to provide a CanvasRobot class."
readme = "README.md"

[project.scripts]
canvasrobot_cli = "canvasrobot.main:run"
urltransform_cli = "canvasrobot.urltransform:run"
